# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys: sbt-cache
      # CC_TEST_REPORTER_ID
      - run: 
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run: 
          name: Run Tests
          command: |
            ./cc-test-reporter before-build
            cat /dev/null | sbt clean coverage test coverageReport
            ./cc-test-reporter format-coverage -t cobertura -d application/server/target/scala-2.12/coverage-report/cobertura.xml
            ./cc-test-reporter upload-coverage
      - store_artifacts:
          path:  application/server/target/scala-2.12/scoverage-report/

      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - ~/.m2

      - run:
          name: dist package
          command: |
                    cat /dev/null | sbt docker:publishLocal
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Start server and check
          command: |
            cd docker
            docker-compose up -d
            docker exec docker_test_1 /var/test/wait.sh
            docker exec docker_test_1 /var/test/test.sh
            docker-compose down
      - run:
          name: Push image to registory
          command: docker push rysh/nephila